version: "3"
services:
  zookeeper:
    build:
      context: .
      dockerfile: zookeeper.Dockerfile
    ports:
      - 2181:2181
    network_mode: "host"
  kafka:
    build:
      context: .
      dockerfile: kafka.Dockerfile
    depends_on:
      - zookeeper
    network_mode: "host"
    ports:
      - 9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
